# Generated by Django 2.2.6 on 2020-08-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMDGCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMO_class', models.FloatField(max_length=4)),
                ('chemical_name', models.CharField(max_length=255)),
            ],
        ),
    ]
