# Generated by Django 2.2.6 on 2020-08-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgs', '0003_auto_20200805_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dg',
            name='example',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dg',
            name='prohibited_reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imdgcode',
            name='IMO_class',
            field=models.IntegerField(max_length=4),
        ),
    ]
