# Generated by Django 2.2.6 on 2020-08-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgs', '0005_auto_20200805_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dg',
            old_name='imdgcode',
            new_name='imdg_code',
        ),
    ]
