# Generated by Django 2.2.6 on 2020-08-05 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dgs', '0006_auto_20200805_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='dg',
            name='writed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
