# Generated by Django 2.2.6 on 2020-08-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgs', '0007_dg_writed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dg',
            old_name='writed_by',
            new_name='user',
        ),
    ]
