# Generated by Django 2.2.6 on 2020-08-08 07:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgs', '0008_auto_20200805_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='dg',
            name='cover',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
