# Generated by Django 2.2.6 on 2020-08-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgs', '0009_dg_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dg',
            old_name='cover',
            new_name='image',
        ),
    ]
