# Generated by Django 2.2.6 on 2020-08-13 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dgs', '0010_auto_20200808_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='dg',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
