# Generated by Django 2.2.6 on 2020-08-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgs', '0011_dg_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dg',
            old_name='title',
            new_name='topic',
        ),
    ]
