# Generated by Django 2.2.6 on 2020-08-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgs', '0012_auto_20200816_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dg',
            old_name='example',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='dg',
            name='prohibited_reason',
        ),
    ]
