# Generated by Django 2.2.6 on 2020-08-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgs', '0013_auto_20200818_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dg',
            name='topic',
            field=models.CharField(max_length=70),
        ),
    ]
