# Generated by Django 2.2.6 on 2020-08-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dgs', '0006_auto_20200805_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('dg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgs.Dg')),
            ],
        ),
    ]
