# Generated by Django 2.2.6 on 2020-08-07 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('who_should_attend', models.CharField(max_length=255)),
                ('course_outline', models.TextField()),
                ('course_objectives', models.TextField()),
                ('accreditation_and_examination', models.CharField(max_length=255)),
                ('course_fees', models.DecimalField(decimal_places=3, max_digits=10)),
                ('course_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.CourseDate')),
            ],
        ),
    ]
