# Generated by Django 2.2.6 on 2020-08-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedate',
            name='time',
        ),
    ]
