# Generated by Django 2.2.6 on 2020-08-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('who_should_attend', models.CharField(max_length=255)),
                ('outline', models.TextField()),
                ('objectives', models.TextField()),
                ('accreditation_and_examination', models.CharField(max_length=255)),
                ('fees', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
