# Generated by Django 2.2.6 on 2020-08-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
